---
title: "Case Study on the GDPs of countries around the world"
author: "Jesse Chen"
date: "October 30, 2016"
output: html_document
---
## Introduction

In this case study we observed the data between a country's GDP ranking and its Income group as defined by the World Bank.

Below you will find the R-Packages and raw data that are required to reproduce the results of this project:
```{R-Dependencies and Initial Data load}
library(repmis)
library(ggplot2)
library(dplyr)
library(plyr)


CountryData <- source_data("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv")

GDP <- source_data("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv")
```

#Clean up

##GDP Clean up
After looking at the CSV file we see that there are some entries that do no possess a valid GDP value.
In addition there are some lines of data at the bottom of the file that we can drop. 
We also drop any columns that we don't need.
Running a str(CleanGDP) we note with some alarm that the ranking is categorized as a character value. We should clear that up to make our lives easier down the line

```{GDP}
CleanGDP <- GDP[GDP$V1!=''& GDP$V2!='' & GDP$V5!='', c(1,2,4,5)]
##Name the variables for ease of use
names(CleanGDP)<-c("CountryCode", "Ranking", "Country", "GDP")
##Purge commas from dollar amounts
CleanGDP$GDP<-as.numeric(gsub(",","",CleanGDP$GDP))


CleanGDP$Ranking<-as.numeric(CleanGDP$Ranking)

str(CleanGDP)
## We should see now that both GDP and Ranking show up as numeric values
```

## Country Clean-up
Looking at the file we can breath a little easier, this file is much cleaner than the GDP file. 
Nonetheless there are lot of unused columns, lets trim them. 

```{Country}
CleanCountry<-CountryData[c(1,2,3)]

```

# Merge the two data sets 

```{Merge}
CleanMerge <- merge(CleanCountry, CleanGDP, by="CountryCode", all=TRUE)
```

## NOTE THAT THIS LAST STEP SHOULD BE DONE AFTER ANSWERING QUESTION 1
After merging we see that some entries on one table do not have matching values on the second table, resulting in some missing values.
In addition we see that the long form of the countries' names have a second column. We are going to purge those. 

```{Erroneous entries}
CleanMerge <- CleanMerge[CleanMerge$Ranking!='' & CleanMerge$GDP!='' & is.na(CleanMerge$Ranking)==FALSE, c(1,2,3,4,6)]
```

#Final Anomaly
A final scan of the data revealed on remaining anomaly: Country Code 'SSD' has a ranking and GDP, but its long form name is blank. 
'SSD' is also missing its income category. 
After we queried the World Bank we discovered that South Sudan is considered a Low Income Country. 

```{Filling in SSD}
CleanMerge$`Long Name`[CleanMerge$CountryCode == "SSD"] <- "South Sudan"
CleanMerge$`Income Group`[CleanMerge$CountryCode == "SSD"] <- "Low income"
```

# Question 1 

```{Question 1}
## Question 1: Finding how many records match:
nrow(CleanMerge[CleanMerge$Ranking!='' & CleanMerge$`Income Group`!='' & is.na(CleanMerge$Ranking)==FALSE, ])
```
We can see from the output that 190 countries' IDs match

# Question 2

```{Question 2}
## Question 2 Finding the 13th lowest country by GDP
CleanMerge<-plyr::arrange(CleanMerge, CleanMerge$GDP)
GDPthirteen<-CleanMerge[13,1]
```
The return value was KNA which corresponds to St. Kitts and Nevis

# Question 3

```{Question 3}
## To find the average GDP rankings for the two high income groups we must parse out the countries by income category
AvgGDP <- CleanMerge[CleanMerge$`Income Group` == "High income: OECD" | CleanMerge$`Income Group` == "High income: nonOECD",c(3,4,5)]
names(AvgGDP) <- c("IncomeGroup","Ranking", "GrossIncome")
attach(AvgGDP)
AvgGDPGroup <- aggregate(AvgGDP[c(2,3)], by=list(IncomeGroup), mean)
detach(AvgGDP)
```
From the results we can see the following:
OECD : Average Ranking: 32.9667 Average GDP: 1483917.1
nonOECD: Average Ranking: 91.91304 Average GDP: 104349.8

# Question 4

```{Question 4}
ggplot(data=CleanMerge, aes(CleanMerge$GDP, fill=CleanMerge$`Income Group`, colour=CleanMerge$`Income Group`)) + geom_density(alpha = 0.7) + ggtitle("GDP by Income Group") 

ggplot(data=CleanMerge, aes(CleanMerge$GDP, fill=CleanMerge$`Income Group`, colour=CleanMerge$`Income Group`)) + geom_density(alpha = 0.7) + ggtitle("GDP by Income Group") + xlim(0,900000)

ggplot(data=CleanMerge, aes(log(CleanMerge$GDP), fill=CleanMerge$`Income Group`, colour=CleanMerge$`Income Group`)) + geom_density(alpha = 0.7) + ggtitle("GDP by Income Group") + xlim(2, 18)
```

We note that the graph is incredibly ugly and extremely difficult to interpret, all the results are mashed towards the value zero. 
We manually add a limit to the x-axis in an attempt to make the graph a little more presentable.
However even with the limit the graph is very difficult to read. We performed a log transform to GDP and see if that helps any.

# Question 5
```{Question 5}

## ntile command is from dplyr.
CleanMerge$Quantile <- ntile(CleanMerge$Ranking,5)

QTable <- table(CleanMerge$Quantile, CleanMerge$`Income Group`)
```
If we view QTable afterwards we can see that there are 5 countries in the 1st quantile of GDP rankings that are also considered lower middle income.

# Conclusion
From analyzing our data we can see that generally a higher GDP is related to having a higher income. However there exists considerable overlap between each income group. In addition we should note that of high income countries they are further broken down in to OECD countries and non-OECD countries. Countries from the latter group on average exihibit lower GDP numbers.